// regulation-today.js — the "Regulation" briefing on the BE AI READY home (and available
// to the tracker). Sister of governance-today.js: same shape, but sourced from OUR OWN
// Regulation tracker (ai_regulations ONLY), so law and regulation get their own headings
// instead of being lumped together. Source of truth is the curated tracker, NOT a live
// web search. Cached in app_settings ('regulation_today') + regulation_today_history;
// regenerated by the regulation_today_digest job or from the admin. Audience is global;
// money in US dollars.
import pool from '../db/pool.js';
import { callClaude } from './claude.js';
import { sourceHeroImage } from './briefing-image.js';
import { recentBriefings, coveredKeys, isCovered, recentlyCoveredBlock } from './briefing-history.js';

const KEY = 'regulation_today';
const ITEM_COUNT = 10;

// Most-recently-updated tracked REGULATIONS, newest first. Excludes unvetted auto-added
// rows (matching the public tracker + the law briefing).
// Auto-publish everything (Paul, 2026-07-08): draw from ALL tracked regulations, matching
// the now-auto-publishing public tracker, so the front page reflects the freshest items.
const VETTED = 'TRUE';
async function recentRegulations(limit) {
  const { rows } = await pool.query(
    `SELECT regulation_name AS name, jurisdiction, status, summary, source_url,
            official_url AS case_url,
            COALESCE(enforcement_date, effective_date, updated_at::date) AS dt, 'regulation' AS kind
       FROM ai_regulations
      WHERE ${VETTED}
      ORDER BY updated_at DESC NULLS LAST LIMIT $1`, [limit]
  ).catch(() => ({ rows: [] }));
  return rows;
}

function sanitizeSummary(raw) {
  let s = (raw || '').trim();
  s = s.replace(/^\s*[-*_]{3,}\s*$/gm, '');
  s = s.replace(/^#{1,6}\s+/gm, '');
  s = s.replace(/\n{3,}/g, '\n\n');
  s = s.split(/\n\s*\n/).map((p) => p.replace(/\s*\n\s*/g, ' ').trim()).filter(Boolean).join('\n\n');
  return s.trim();
}

function buildHeadlines(items) {
  const seen = new Set(); const out = [];
  for (const it of items) {
    const url = it.source_url || it.case_url || null;
    const key = url || it.name;
    if (key && !seen.has(key)) { seen.add(key); out.push({ title: it.name, url }); }
  }
  return out.slice(0, 6);
}

export async function generateRegulationToday() {
  // Pull a wider pool than we'll feature, so quiet days still have un-repeated items.
  const items = await recentRegulations(ITEM_COUNT + 10);
  if (!items.length) return null;   // nothing tracked yet — honest empty (no invention)

  // Close the repeat loop: fresh (not recently briefed) items first, and tell the
  // model what it already led with.
  const history = await recentBriefings('regulation_today_history').catch(() => []);
  const covered = coveredKeys(history);
  const fresh = [], stale = [];
  for (const it of items) {
    (isCovered(covered, { url: it.source_url || it.case_url, title: it.name }) ? stale : fresh).push(it);
  }
  const ordered = [...fresh, ...stale].slice(0, ITEM_COUNT);

  const sourceList = ordered.map((it) => {
    const meta = [it.jurisdiction, it.status].filter(Boolean).join(', ');
    const sum = (it.summary || '').replace(/\s+/g, ' ').trim().slice(0, 220);
    return `- ${it.name}${meta ? ` (${meta})` : ''}${sum ? `: ${sum}` : ''}`;
  }).join('\n');

  const writeSystem =
    'You write a daily "AI Regulation" briefing for small and medium businesses on the Be AI Ready platform. ' +
    'Audience: non-technical owners and managers at organisations of any size, anywhere in the world — do ' +
    'NOT assume a specific country or region, and do not single out any one nationality of business. Give ' +
    'any monetary amounts in US dollars ($). Tone: plain, calm, concrete — no hype, no jargon. You are given ' +
    'regulations and standards from OUR OWN curated AI Regulation tracker. Output ONLY the briefing prose and ' +
    'nothing else: 90–110 words, one or two short paragraphs. Pick the few most significant items and say, in ' +
    'everyday terms, what each practically means for a business using AI. Use ONLY the items provided — do ' +
    'not add, rename, merge or invent any regulation, standard, body, company or model, and do not pull in ' +
    'anything from outside this list. Do NOT restate these instructions, write a preamble or heading, use ' +
    'markdown or bullets, or produce more than one version.';
  const writeUser = `From our AI Regulation tracker (most recently updated, newest first):\n\n${sourceList}${recentlyCoveredBlock(history)}\n\nWrite the briefing now.`;
  const text = await callClaude({ system: writeSystem, userContent: writeUser, maxTokens: 320, temperature: 0.4 });

  const value = {
    summary: sanitizeSummary(text),
    headlines: buildHeadlines(ordered),
    source: 'tracker',
    generated_at: new Date().toISOString(),
  };
  try { value.hero_image = await sourceHeroImage('regulation', value.headlines); } catch (e) { console.warn('[regulation-today:image]', e.message); }
  await pool.query(
    `INSERT INTO app_settings (key, value, updated_at) VALUES ($1, $2, NOW())
       ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW()`,
    [KEY, JSON.stringify(value)]
  );
  if (value.summary) {
    const digestDate = value.generated_at.slice(0, 10);
    await pool.query(
      `INSERT INTO regulation_today_history (digest_date, summary, headlines, generated_at)
       VALUES ($1, $2, $3::jsonb, $4)
       ON CONFLICT (digest_date) DO UPDATE
         SET summary = EXCLUDED.summary, headlines = EXCLUDED.headlines, generated_at = EXCLUDED.generated_at`,
      [digestDate, value.summary, JSON.stringify(value.headlines || []), value.generated_at]
    ).catch((e) => console.error('[regulation-today:history]', e.message));
  }
  return value;
}

export async function getRegulationTodayHistory(limit = 60) {
  const { rows } = await pool.query(
    `SELECT digest_date, summary, headlines, generated_at
       FROM regulation_today_history ORDER BY digest_date DESC LIMIT $1`, [limit]);
  return rows;
}

export async function getRegulationToday({ generateIfEmpty = false } = {}) {
  const { rows } = await pool.query('SELECT value FROM app_settings WHERE key = $1', [KEY]);
  if (rows.length) return rows[0].value;
  if (generateIfEmpty) { try { return await generateRegulationToday(); } catch { return null; } }
  return null;
}
